name: Check for broken links

on:
  push:
    branches:
      - master
      - main
    paths:
      - "site/**"
      - ".github/workflows/broken-links.yml"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "site/**"
      - ".github/workflows/broken-links.yml"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --offline --verbose --no-progress 'site/**/*.html'
